Repository vocascan/documentation, pull requests merged in 2021-11, with the labels that each got.

#5 added print style media query
  docs/_media/style/style.css
Labels: kind/style

#7 read changelog from repository
  docs/_media/plugins/docsify-toc/toc.js
  docs/_media/style/style.css
  docs/index.html
  docs/vocascan-desktop/changelog.md
  docs/vocascan-server/changelog.md
Labels: enhancement

#6 added maintainers page
  docs/_sidebar.md
  docs/contributing/maintainers.md
Labels: enhancement

#9 autolink plugin
  docs/_media/plugins/autoLink/autoLink.js
  docs/index.html
Labels: enhancement

#4 cli documentation
  docs/_media/style/style.css
  docs/_sidebar.md
  docs/vocascan-server/cli.md
Labels: documentation, enhancement

#10 enable and default logger config
  docs/vocascan-server/configuration.md
  docs/vocascan-server/logging.md
Labels: documentation, enhancement

#12 tag explanation/update guide
  docs/vocascan-server/installation/docker.md
  docs/vocascan-server/installation/pm2.md
  docs/vocascan-server/installation/traefik.md
Labels: enhancement

#14 Readme alias
  docs/_media/plugins/docsify-toc/toc.js
  docs/_media/style/style.css
  docs/_sidebar.md
  docs/index.html
Labels: enhancement

#15 zoom plugin; docsify tabs; improved coverpage
  docs/_coverpage.md
  docs/_media/style/style.css
  docs/index.html
  docs/vocascan-server/installation/docker.md
Labels: enhancement

#13 Docs/readme
  docs/_media/logo/vocascan-cover.svg
  docs/home.md
Labels: documentation
